---
- name: get spark
  get_url:
    url: "{{spark_url}}"
    dest: "{{spark_tar}}"
    checksum: md5:"{{spark_md5}}"
  
- name: extact spark
  unarchive:
    src: "{{spark_tar}}"
    dest: "{{spark_inst_dir}}"
    remote_src: yes

- name: Clean artifact path
  file:
    state: absent
    path: "{{spark_tar}}"
    remote_src: yes
